import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./companents/Header/Header";
import Footer from "./companents/Footer/Footer";
import Form from "@/form/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TourLand",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Header/>

        <main className="flex-1">
          <Form/>
          {children}
        </main>

        <Footer/>
      </body>
    </html>
  );
}